In [20]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [21]:
import warnings
warnings.filterwarnings('ignore')

### 1. Set Default Data Repo and load data

In [22]:
X = pd.read_csv('X_val.csv')
y = pd.read_csv('y_val.csv')

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [24]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
5655,1,1,0,0,0.126761,1,0,0,0,1,...,0,1,0,1,0,0,0,1,0,0
101,1,0,1,1,0.000000,1,0,0,0,0,...,0,0,1,1,0,0,0,0,1,0
2616,0,0,1,0,0.985915,1,0,0,1,1,...,1,0,0,0,0,1,0,1,0,0
392,1,1,0,0,0.014085,1,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1323,0,0,1,0,0.816901,1,1,0,0,1,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3046,1,0,1,1,0.985915,1,1,1,1,1,...,1,0,0,0,0,1,1,0,0,0
1725,0,0,0,0,0.000000,1,1,0,0,0,...,1,0,0,1,0,0,0,0,1,0
4079,1,0,1,0,1.000000,1,1,1,1,1,...,1,0,0,0,0,1,0,1,0,0
2254,1,0,0,0,0.098592,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
2915,1,0,1,0,1.000000,1,0,1,1,1,...,1,0,0,0,0,1,0,0,0,1

In [25]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
type(y_test)

pandas.core.frame.DataFrame

In [27]:
pd.DataFrame(X_test).to_csv('X_test_val.csv', index=False)

### 2. Model creation

In [30]:
type(y_train)

pandas.core.frame.DataFrame

In [31]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization
# from torch.utils.data import Dataset, DataLoader
import tensorflow as tf


model = Sequential()
model.add(Dense(4 , activation='relu'))
model.add(BatchNormalization())
model.add(Dense(5, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


model.fit(X_train, y_train.values)

176/176 [==============================] - 1s 1ms/step - loss: 0.6549 - accuracy: 0.6101

### 3. Model training and validation

### Save model binary

In [11]:
import torch
X_train = torch.Tensor((X_train))

In [12]:
type(X_train)

torch.Tensor

In [32]:
model.save('model.h5')

In [33]:
import tensorflow as tf
mod = tf.keras.models.load_model('model.h5')